name: Importar template Zabbix

on:
  push:
    branches: [master]
    paths:
      - 'templates/**'

jobs:
  importar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 

      - name: Debug - Verificar segredos e arquivos
        run: |
          echo "TOKEN_ZABBIX está definido? ${{ secrets.TOKEN_ZABBIX != '' }}"
          git diff --name-only HEAD~1 HEAD -- templates/

      - name: Instalar dependências
        working-directory: scripts
        run: pip install -r requirements.txt

      - name: Rodar importador Zabbix
        working-directory: scripts
        env:
          TOKEN_ZABBIX: ${{ secrets.TOKEN_ZABBIX }}
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- templates/)
          echo "Arquivos a processar:"
          echo "$CHANGED_FILES"
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "Nenhum arquivo para processar"
            exit 0
          fi
          
          python3 template_alter.py $CHANGED_FILES