name: Importar template Zabbix

on:
  push:
    branches: [master]
    paths:
      - 'templates/**'

jobs:
  importar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Instalar dependências
        run: pip install -r ./scripts/requirements.txt

      - name: Rodar importador Zabbix
        run: |
          python3 ./scripts/template_alter.py