name: Importar template Zabbix

on:
  push:
    branches: [master]
    paths:
      - 'templates/**'

jobs:
  importar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Instalar dependências
        working-directory: ./scripts
        run: pip install -r requirements.txt

      - name: Rodar importador Zabbix
        working-directory: ./scripts
        run: |
          python3 template_alter.py