name: Importar template Zabbix

on:
  push:
    branches: [master]
    paths:
      - 'templates/**'

jobs:
  importar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 

      - name: Debug - Verificar segredos e arquivos
        run: |
          echo "TOKEN_ZABBIX está definido? ${{ secrets.TOKEN_ZABBIX != '' }}"
          cat $(git diff --name-only HEAD~1 HEAD -- templates/)

      - name: Instalar dependências
        working-directory: scripts
        run: pip install -r requirements.txt

      - name: Rodar importador Zabbix
        env:
          TOKEN_ZABBIX: ${{ secrets.TOKEN_ZABBIX }}
        run: |
          python3 scripts/template_alter.py $(git diff --name-only HEAD~1 HEAD -- templates/)